project_id = "oykpslopjzjhfwepxowp"

[functions.send-notification]
verify_jwt = true

[functions.auto-complete-jobs]
verify_jwt = false

[functions.send-invoice]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = true

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.autopay-post-jobs]
verify_jwt = false

[functions.autopay-provider-payouts]
verify_jwt = false

[functions.cleanup-old-jobs]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.create-payment-url]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false
